---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk
inputs:
  - name: repo
  - name: version
outputs:
  - name: out
run:
  path: /bin/bash
  args:
    - repo/concourse/tasks/build-and-upload.sh

caches:
  - path: .gradle/