---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk

inputs:
  - name: version
  - name: repo

outputs:
  - name: updated-version

run:
  path: repo/concourse/tasks/generate-version.sh

params:
  GIT_EMAIL:
  GIT_NAME:

caches:
  - path: .gradle/
  - path: .m2/