---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springcloud/pipeline-base

inputs:
  - name: version
  - name: repo

outputs:
  - name: updated-version

run:
  path: repo/concourse/tasks/generate-version.sh

params:
  GIT_EMAIL:
  GIT_NAME:
